#!/bin/bash

total_seconds=""

while getopts "s:m:" opt; do
case "$opt" in
    s) total_seconds=$(( $total_seconds + $OPTARG ));;
    m) total_seconds=$(( $total_seconds + $OPTARG * 60 ));;
    \?);;
esac
done

while [ $total_seconds -gt 0 ]; do
    echo "$total_seconds"
    sleep 1s
    total_seconds=$(( $total_seconds - 1 ))
done
echo "$result"